theme = "gruvbox-material"

[editor]
line-number = "relative"
completion-timeout = 5
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
